import type { Metadata } from "next";

import "./globals.css";
import { PlayfairDisplay } from "./components/Fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={PlayfairDisplay.className}>{children}</body>
    </html>
  );
}
